name: CI
on: workflow_dispatch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: setup java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: checkout repo
      uses: actions/checkout@v4
    - name: unit test
      run: mvn test
    - name: checkstyle test
      run: mvn checkstyle:checkstyle
    - name: upload reports to sonar
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_URL }}
        ORG_KEY: ${{ secrets.ORG_KEY }}
        PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
      with:
        args: >
          -Dsonar.projectKey=${{ env.PROJECT_KEY }}
          -Dsonar.organization=${{ env.ORG_KEY }}
          -Dsonar.projectVersion=${{ github.event.repository.updated_at}}
          -Dsonar.java.binaries=target/classes/com/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_URL }}

    - name: build and push image to AWS ECR
      uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: ${{ vars.ECR_REPOSITORY }}
        region: ${{ vars.AWS_REGION }}
        tags: latest,${{ GITHUB_RUN_NUMBER }}
    
    ## add updating the image in the AWS ECS service




