name: CI
on: workflow_dispatch

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: setup java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: checkout repo
      uses: actions/checkout@v4
    - name: unit test
      run: mvn test
    - name: checkstyle test
      run: mvn checkstyle:checkstyle
    - name: upload reports to sonar
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        ORG_KEY: ${{ secrets.ORG_KEY }}
        PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
        SONAR_URL: ${{ vars.SONAR_URL }}
      with:
        args: >
          -Dsonar.host.url=${{ env.SONAR_URL }}
          -Dsonar.projectKey=${{ env.PROJECT_KEY }}
          -Dsonar.organization=${{ env.ORG_KEY }}
          -Dsonar.java.binaries=target/classes/com/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml




